### ISSUE TITLE
odoh not working with all targets

### ISSUE THREAD

**Issue by mschirrmeister** [natesales/q#2]
Hello,

does the odoh support only works with specific versions/implementations?
I am using the [`doh-server`](https://github.com/jedisct1/doh-server) as a **target** and when I query it, I always get the error `target provided no valid odoh configs`.

```
q a aaaa example.com --server=https://odoh-target.marco.cx --odoh-proxy=https://odoh-relay.marco.cx
FATA[0002] target provided no valid odoh configs
```

It works works fine when I use other **odoh** clients.

**Comment by natesales** [comment]
Apologies for the (very) long delay here.

Release v0.4.2 addresses this problem.

```bash
~ ▴ sudo apt list q
Listing... Done
q/unknown,now 0.4.2 amd64 [installed]
q/unknown 0.4.2 arm64
~ ▴ q a aaaa example.com --server=https://odoh-target.marco.cx --odoh-proxy=https://odoh-relay.marco.cx
example.com. 23h38m57s A 93.184.216.34
example.com. 23h38m58s AAAA 2606:2800:220:1:248:1893:25c8:1946
```

**Comment by mschirrmeister** [comment]
No problem and thank you very much for the update and release. Updated my local client and it works for me now as well.
