### ISSUE TITLE
Color codes output

### ISSUE THREAD

**Issue by uggyuggy** [natesales/q#20]
Hi,
Thank's for sharing `q`

Noticed output to file keeps the color codes.

```
$  q -V
https://github.com/natesales/q version 0.5.8 (e84c6bbbfaa762f904ffbbd402f83630fa67589e 2022-04-18T20:59:46Z)
$
$ q ns eff.org > /tmp/a
$
$ cat -A /tmp/a | head -1
^[[1;34meff.org.^[[0m ^[[1;32m1h43m58s^[[0m ^[[1;35mNS^[[0m ns4.eff.org.$
$
```

Sure we could easily strip the color codes from the output.
This may be useful (as implemented into some other programs) to "detect" if the output is into the console (add color) or not (remove color codes) and/or add some `--[no]color` option to force

**Comment by natesales** [comment]
Thanks for the report! Fixed in v0.6.0

```bash
~ ▴ q -V
https://github.com/natesales/q version 0.6.0 (6a61a94b471700232f14d955dc738d2ceab4d181 2022-04-24T06:17:58Z)
~ ▴ q ns eff.org > /tmp/a
~ ▴ cat -A /tmp/a | head -1
eff.org. 2h0m0s NS ns4.eff.org.$
```
