### ISSUE TITLE
QUIC port number

### ISSUE THREAD

**Issue by mdavids** [natesales/q#24]
Since the ratification of DNS over QUIC (RFC9250), the official port for DoQ is 853. Would it make sense to change this default?

https://github.com/natesales/q/blob/d0b049f0ce13676accc5423daa3dc91ae1b89395/main.go#L226

References:

https://datatracker.ietf.org/doc/html/rfc9250#section-4.1.1
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=853

**Comment by natesales** [comment]
Good point! Released in v0.8.0
