### ISSUE TITLE
unable to look up git.schwanenlied.me

### ISSUE THREAD

**Issue by van-scott** [natesales/q#25]
Download the project and compile, the following problems occur：
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/40486630/173797789-ddb58290-769a-45a9-993c-938b9b26c9aa.png">

I found that the domain name git.schwanenlied.me is nxdomain

**Comment by natesales** [comment]
This was an issue with the go-hpke dependency and has been fixed in [005c2a9](https://github.com/natesales/q/commit/005c2a9f098e415338e683fc80c1e0c11c94b4db).

**Comment by lasombra** [comment]
Sorry to reopen this issue, but I just cloned the repository and am seeing the same error
