### ISSUE TITLE
Unable to build: x448 indirect dependency hosting infra is down

### ISSUE THREAD

**Issue by Seirdy** [natesales/q#29]
The indirect dependency `git.schwanenlied.me/yawning/x448.git v0.0.0-20170617130356-01b048fb03d6` cannot be downloaded because the host seems unreachable. This makes it impossible to build q.

Related issue from a year ago: https://github.com/lightninglabs/faraday/issues/131

Given how long ago that issue was filed, this doesn't seem like a temporary problem.

**Comment by natesales** [comment]
This is an upstream issue unfortunately; you might try opening an issue in https://github.com/cisco/go-hpke
