### ISSUE TITLE
Not working correctly in Powershell 7.2.6 on Windows 10

### ISSUE THREAD

**Issue by CorruptedPixl** [natesales/q#32]
Hi there, thanks for sharing this project!
I ran into an issue when trying to run q on Windows.

When installing with Go [`go install github.com/natesales/q@latest`] and running `q example.com` the only output I get are debug messages.

_Running in Powershell 7.2.6_
![image](https://user-images.githubusercontent.com/38385453/188336879-9697055e-aced-4ad5-89be-0e2124559344.png)

**What I've tried**

- Running the binaries instead of installing via Go, I got no output at all that way.
- Installing an older version [`v0.8.0`], same issue
- Running q with commandprompt instead of powershell
   I still get the debug messages, but I do also get an output!

_Running in cmd_
![image](https://user-images.githubusercontent.com/38385453/188336915-8ed403c1-5fe1-45ae-80f2-a15d0ceb991d.png)

I'm not sure why I'm getting the debug messages when I install via Go, and not in the binaries. Am I missing an option somewhere?
Im also not sure why it refuses to work in Powershell. If I can help let me know, I'd love to try this out as you intended it to work!

**Comment by natesales** [comment]
I have almost no powershell experience, but is it possible that it's running a different q binary entirely? What does the output of `q -V` look like in both cmd and powershell?

**Comment by CorruptedPixl** [comment]
Both cmd and powershell return `https://github.com/natesales/q version dev (unknown unknown)`.
It should be the only binary on my system as I've deleted the other tries.

**Comment by natesales** [comment]
Very strange. Do other transport protocols work? `q example.com @1.1.1.1 -f json -v`

**Comment by CorruptedPixl** [comment]
Hm, again different behaviour between cmd and Powershell.
The command you posted above works fine in cmd, but in powershell I get this error:
![image](https://user-images.githubusercontent.com/38385453/188942907-43605fcd-73c9-4a17-ba4d-7b3341fa5621.png)

After changing the @ to -s (for server, that is the correct flag, right?) I get the same null response as before.
![image](https://user-images.githubusercontent.com/38385453/188943028-d90d044d-fec7-449d-b00c-7314482af0d5.png)


I did take a look at the cloudflare docs and tried some requests out myself and I noticed that when using `accept/dns-message` I get a bad request back via curl, but when using `accept/dns-json` I do get valid json back. Could that maybe be part of the issue?
I can see in the source code where this chance would have to be made, but I'm not experienced enough with Go to edit and run it myself. Is there an easy way to test this out myself?

**Comment by natesales** [comment]
Seems that powershell is interpreting the @ symbol as part of it's own syntax - I don't have any experience with powershell but it looks like the @ symbol can mean [multiple things](https://stackoverflow.com/a/32915159) in powershell land.

Regardless, I'm still not sure why you aren't getting any data back. Can you grab a packet capture and see what's happening on the wire? Lets stick with UDP (-s 1.1.1.1) to make debugging easier.

**Comment by CorruptedPixl** [comment]
We're definitely on the right track here.

Looking at the packets captured from cmd firstly, and then powershell, I can see that cmd submits the correct queries `A example.com` etc...
However the ones below that are from powershell and seem to submit a query for the path of where the q executable is, have a look.
![image](https://user-images.githubusercontent.com/38385453/188968639-ed8934a7-1ceb-495a-b37f-3181257dbfc1.png)

The query that powershell submits is something like this `A c:users[usernamehere]gobinq.exe` which so happens to be the path for where the executable is on my system.

I think it might be that powershell interprets some arguments differently and somehow submits the wrong one? I have no clue how tho, but I'll give the code another look.

**Comment by CorruptedPixl** [comment]
I've had a look at the source and I think I might have found a way to fix this.

If I understand it correctly, the parser loops over all the args and sets them if they pass some checks. I think the path of the executable passes the check for where the query name is set and then runs off with that without actually setting the correct one.

This might not be the best solution, but what if you added another check for if the string contained `C:Users` in [this if statement](https://github.com/natesales/q/blob/main/main.go#L383-L391)?

This wouldn't account for the binary being on another drive, or not in the Users directory, but that might be way to fix this in the meantime. Then again, I'm not sure this _would_ actually fix this issue, what are your thoughts?

**Comment by CorruptedPixl** [comment]
I read some Go docs and managed to try it out myself.

I [added a check to the queryname](https://github.com/CorruptedPixl/q/commit/fc6bc93aeadf907048b66b902cea231f1f90bd6f) which checks if the current arg string contains `.exe` since this indicates it's been given the path of the executable, and not the domain name.
I ran this in cmd and Powershell and they both work fine however I see that you've also set up some testing, but I'll leave that to you since it's probably more your expertise.

Personally I think instead of doing all those separate checks, maybe a single regex check would suffice? The regex could test if the current arg is a valid domain name or not, do you think that could work?

Anyhow, could you check if fix this still works on linux etc? If you have any remarks, I'm happy to hear them, cheers!

**Comment by natesales** [comment]
Thanks for the fix! That looks like a great solution to me. I made one minor comment on #33  which I think should still work identically.

**Comment by CorruptedPixl** [comment]
Thanks! I tried out the comment, but I ran into issues with cmd doing the same thing Powershell was doing.

I suggested on #33 we check for `.exe` since that's something that's both in what cmd parses (just `q.exe`) and what powershell parses (the full `C:Users/path/to/q.exe`).

Let me know what you think!

**Comment by natesales** [comment]
Sorry for the delay here. I just merged #33, ok to close this?

**Comment by CorruptedPixl** [comment]
Yes, good to close!
