### ISSUE TITLE
q does not work well in Windows10

### ISSUE THREAD

**Issue by nasaboy** [natesales/q#45]
Unable to read the default DNS address, causing the query to fail
It is normal in the linux system, and the default DNS address can be read from /etc/resolv
![微信截图_20230301190209](https://user-images.githubusercontent.com/5997682/222121391-09382f79-615e-43a2-86c1-726eef825dfe.png)

**Comment by natesales** [comment]
Something is terminating your connection to cloudflare-dns.com. Can you run a packet capture to see what might be happening?

**Comment by nasaboy** [comment]
> Something is terminating your connection to cloudflare-dns.com. Can you run a packet capture to see what might be happening?

Yes,I'm in China,because the great fire wall.cloudflare dns should be blocked

**Comment by natesales** [comment]
I've added the Q_DEFAULT_SERVER environment variable which will allow you to set an alternate default server.
