### ISSUE TITLE
Problems on DNS server URL format

### ISSUE THREAD

**Issue by showgood163** [natesales/q#66]
Hi, there.

I'm having problems testing URLs for DNS servers that contain one or more colons. It looks like `q` is recognizing the string after the first colon as a port number, which is unexpected.

Here is an example:

```
xx@yy ~ % q -V
https://github.com/natesales/q version 0.12.0 (20119b4c88d1af96acd0a4c4dceb3082c80d28c3 2023-09-08T20:19:29Z)
xx@yy ~ % q youtube.com @https://local.host/1:89==:64fx
FATA[0000] creating http request to https://local.host:89==/1?dns=MBMBAAABAAAAAAAAB3lvdXR1YmUDY29tAAABAAE: parse "https://local.host:89==/1?dns=MBMBAAABAAAAAAAAB3lvdXR1YmUDY29tAAABAAE": invalid port ":89==" after host
```

**Comment by natesales** [comment]
A temporary fix is to URL encode your server URL path:

```
$ q youtube.com @https://local.host/1%3A89%3D%3D%3A64fx -v
DEBU[0000] Name: youtube.com                            
DEBU[0000] RR types: [A AAAA NS MX TXT CNAME]           
DEBU[0000] Using HTTP(s) transport: https://local.host:443/1%3A89%3D%3D%3A64fx 
DEBU[0000] [http] sending GET request to https://local.host:443/1%3A89%3D%3D%3A64fx?dns=znoBAAABAAAAAAAAB3lvdXR1YmUDY29tAAAFAAE
<truncated>
```

I'll keep this ticket open to fix the underlying parser problem.

Out of curiosity, what does `/1:89==:64fx` represent in the context of your DNS server?

**Comment by showgood163** [comment]
I'll have a test asap.

`:` is used as the delimiter for [auth in serverless-dns](https://github.com/serverless-dns/serverless-dns#auth).

**Comment by natesales** [comment]
Can you try on v0.15.1? The old server address parser had some hacky code that needed to be rewritten anyway, so I've cleaned it up in 14abd7388d44439e343146583953bfeff9e9705b

**Comment by showgood163** [comment]
My tests shows no failure.

**Comment by natesales** [comment]
Great! Closing.
